### ISSUE TITLE
Running tests fails when trying to create Tenant

### ISSUE THREAD

**Issue by pmontepagano** [Corvia/django-tenant-users#19]
I am trying to run tests on a project that uses django-tenant-schemas and django-tenant-users.

I've written a very basic test like this:

```
from tenant_schemas.test.cases import TenantTestCase
from .models import WorkshopCost

class BasicTest(TenantTestCase):
	def test_example(self):
		w = WorkshopCost.objects.create(cost=55.5)
		self.assertIs(w.cost, 55.5)
```

but when running `./manage.py test`, I get this error:

```
ERROR: setUpClass (workshops.tests.BasicTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/django/db/backends/utils.py", line 65, in execute
    return self.cursor.execute(sql, params)
psycopg2.IntegrityError: null value in column "owner_id" violates not-null constraint
DETAIL:  Failing row contains (4, tenant.test.com, test, , 2018-05-04 20:54:04.159152+00, 2018-05-04 20:54:04.159162+00, , , null).


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/tenant_schemas/test/cases.py", line 28, in setUpClass
    cls.tenant.save(verbosity=0)  # todo: is there any way to get the verbosity from the test command here?
  File "/usr/local/lib/python3.6/site-packages/tenant_users/tenants/models.py", line 80, in save
    super(TenantBase, self).save(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/tenant_schemas/models.py", line 67, in save
    super(TenantMixin, self).save(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/django/db/models/base.py", line 808, in save
    force_update=force_update, update_fields=update_fields)
  File "/usr/local/lib/python3.6/site-packages/django/db/models/base.py", line 838, in save_base
    updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
  File "/usr/local/lib/python3.6/site-packages/django/db/models/base.py", line 924, in _save_table
    result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
  File "/usr/local/lib/python3.6/site-packages/django/db/models/base.py", line 963, in _do_insert
    using=using, raw=raw)
  File "/usr/local/lib/python3.6/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/django/db/models/query.py", line 1076, in _insert
    return query.get_compiler(using=using).execute_sql(return_id)
  File "/usr/local/lib/python3.6/site-packages/django/db/models/sql/compiler.py", line 1107, in execute_sql
    cursor.execute(sql, params)
  File "/usr/local/lib/python3.6/site-packages/django/db/backends/utils.py", line 65, in execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.6/site-packages/django/db/utils.py", line 94, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/usr/local/lib/python3.6/site-packages/django/utils/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.6/site-packages/django/db/backends/utils.py", line 65, in execute
    return self.cursor.execute(sql, params)
django.db.utils.IntegrityError: null value in column "owner_id" violates not-null constraint
DETAIL:  Failing row contains (4, tenant.test.com, test, , 2018-05-04 20:54:04.159152+00, 2018-05-04 20:54:04.159162+00, , , null).
```

With @ivissani we've been thinking that maybe you need to subclass django-tenant-schema's `TenantTestCase` and modify the `setUpClass` method, so that it uses `tenant_users.tenants.tasks. provision_tenant` to create the test tenant?

**Comment by Viatrak** [comment]
Can you submit a PR for this?

**Comment by ExTexan** [comment]
Is this being or has this been fixed in the current version?  I'm running into the same issue.

**Comment by Viatrak** [comment]
Nothing has been changed with respect to this yet -- a pull request with fixes/changes is welcome!

**Comment by pickyuptruck** [comment]
Hi, I'm facing this problem with django_tenants too

**Comment by AntMam** [comment]
Has anyone figured out how to get this to work with django-tenants? Is @pmontepagano 's idea the right direction to try and solve this?

**Comment by AntMam** [comment]
For anyone who ends up here, this is how i solved it (using django-tenants):

# tests.py
`
from users.models import TenantUser
from django_tenants.test.cases import TenantTestCase


class BaseTest(TenantTestCase):
    @classmethod
    def setup_tenant(cls, tenant):
        """
        Add any additional setting to the tenant before it get saved. This is required if you have
        required fields.
        """

       # This creates the tenant user needed for "owner_id"
       tenant_user = TenantUser.objects.create(
                name="admin1", email="admin1@gmail.com"
            )
        tenant.name = "public"
        tenant.email = "admin@gmail.com"

        # For django-tenant-users
        tenant.owner_id = 1
        tenant.tenants = [1]

        return tenant`

**Comment by AntMam** [comment]
For anyone who ends up here, I got it to work using [django-tenants docs on testing]("https://django-tenants.readthedocs.io/en/latest/test.html"). Since django-tenant-users requires a tenant to have an "owner_id", you create the tenant user, then add the id of the user (1) as the tenant.owner_id:

``` class BaseTest(TenantTestCase):
    @classmethod
    def setup_tenant(cls, tenant):
        """
        Add any additional setting to the tenant before it get saved. This is required if you have
        required fields.
        """

        # Creates the tenant user needed to set up tenant.owner_id

        tenant_user = TenantUser.objects.get(email="admin1@gmail.com")
        tenant.name = "public"
        tenant.email = "admin@gmail.com"

        # For django-tenant-users

        tenant.owner_id = 1
        tenant.tenants = [1]
        return tenant```
