### ISSUE TITLE
Error creating public tenant

### ISSUE THREAD

**Issue by dpthornton** [Corvia/django-tenant-users#23]
Hi,

Just getting setup and using for the first time, and encountered the below error creating the public tenant, looks like might be a compatibility issue, is there a version of tenant-schemas I should stick to? 

>>> create_public_tenant("localhost","demo")
()
{'force_insert': True, 'using': 'default'}
Traceback (most recent call last):
  File "/Users/danielthornton/Documents/liclipse_workspace/teamtalk-env/lib/python3.7/site-packages/django/db/backends/utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)
psycopg2.IntegrityError: null value in column "paid_until" violates not-null constraint
DETAIL:  Failing row contains (1, localhost, public, , 2018-09-12 15:54:44.797985+00, 2018-09-12 15:54:44.798003+00, Public Tenant, null, null, 2018-09-12, 1).

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/Users/danielthornton/Documents/liclipse_workspace/teamtalk-env/lib/python3.7/site-packages/tenant_users/tenants/utils.py", line 36, in create_public_tenant
    owner=profile)
  File "/Users/danielthornton/Documents/liclipse_workspace/teamtalk-env/lib/python3.7/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Users/danielthornton/Documents/liclipse_workspace/teamtalk-env/lib/python3.7/site-packages/django/db/models/query.py", line 413, in create
    obj.save(force_insert=True, using=self.db)
  File "/Users/danielthornton/Documents/liclipse_workspace/teamtalk-env/lib/python3.7/site-packages/tenant_users/tenants/models.py", line 80, in save
    super(TenantBase, self).save(*args, **kwargs)
  File "/Users/danielthornton/Documents/liclipse_workspace/teamtalk-env/lib/python3.7/site-packages/tenant_schemas/models.py", line 69, in save
    super(TenantMixin, self).save(*args, **kwargs)
  File "/Users/danielthornton/Documents/liclipse_workspace/teamtalk-env/lib/python3.7/site-packages/django/db/models/base.py", line 717, in save
    force_update=force_update, update_fields=update_fields)
  File "/Users/danielthornton/Documents/liclipse_workspace/teamtalk-env/lib/python3.7/site-packages/django/db/models/base.py", line 747, in save_base
    updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
  File "/Users/danielthornton/Documents/liclipse_workspace/teamtalk-env/lib/python3.7/site-packages/django/db/models/base.py", line 830, in _save_table
    result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
  File "/Users/danielthornton/Documents/liclipse_workspace/teamtalk-env/lib/python3.7/site-packages/django/db/models/base.py", line 868, in _do_insert
    using=using, raw=raw)
  File "/Users/danielthornton/Documents/liclipse_workspace/teamtalk-env/lib/python3.7/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Users/danielthornton/Documents/liclipse_workspace/teamtalk-env/lib/python3.7/site-packages/django/db/models/query.py", line 1133, in _insert
    return query.get_compiler(using=using).execute_sql(return_id)
  File "/Users/danielthornton/Documents/liclipse_workspace/teamtalk-env/lib/python3.7/site-packages/django/db/models/sql/compiler.py", line 1285, in execute_sql
    cursor.execute(sql, params)
  File "/Users/danielthornton/Documents/liclipse_workspace/teamtalk-env/lib/python3.7/site-packages/django/db/backends/utils.py", line 100, in execute
    return super().execute(sql, params)
  File "/Users/danielthornton/Documents/liclipse_workspace/teamtalk-env/lib/python3.7/site-packages/django/db/backends/utils.py", line 68, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/Users/danielthornton/Documents/liclipse_workspace/teamtalk-env/lib/python3.7/site-packages/django/db/backends/utils.py", line 77, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/Users/danielthornton/Documents/liclipse_workspace/teamtalk-env/lib/python3.7/site-packages/django/db/backends/utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)
  File "/Users/danielthornton/Documents/liclipse_workspace/teamtalk-env/lib/python3.7/site-packages/django/db/utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/Users/danielthornton/Documents/liclipse_workspace/teamtalk-env/lib/python3.7/site-packages/django/db/backends/utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)
django.db.utils.IntegrityError: null value in column "paid_until" violates not-null constraint
DETAIL:  Failing row contains (1, localhost, public, , 2018-09-12 15:54:44.797985+00, 2018-09-12 15:54:44.798003+00, Public Tenant, null, null, 2018-09-12, 1).

**Comment by dpthornton** [comment]
Sorry my dumbness, still had the old Client model in as defined in the tenant schemas documentation.
