### ISSUE TITLE
Error creating Tenants in app or command line

### ISSUE THREAD

**Issue by mronoffon** [Corvia/django-tenant-users#33]
Tenants can not be created when using 'create_tenant' when using "./manage.py create_tenant".  I even tried
 
These are the fields appearing...

schema name: test
Tenant URL Name: test
owner: testowner
modified: 
name: test
description: test

which then returns: **"ValueError: Cannot assign "'testowner": "Client.owner" must be a "TenantUser" instance." is the result.**  

 I also tried to create a tenant with "tenant = Client(schema_name='tenant1', name='My First Tenant')..." and got...

**IntegrityError: null value in column "owner_id" violates not-null constraint
DETAIL:  Failing row contains (4, tenant1, , 2019-08-15 23:59:12.722278+00, 2019-08-15 23:59:12.721594+00, My First Tenant, null, 2019-08-15, null).**

How should I handle the 'owner' field, which is a Foreign Key, at the command line?  There
are no tests.
 

--------- Full traceback
Traceback (most recent call last):
  File "./manage.py", line 33, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.7/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.7/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.7/site-packages/django/core/management/base.py", line 323, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.7/site-packages/django/core/management/base.py", line 364, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python3.7/site-packages/django_tenants/management/commands/create_tenant.py", line 58, in handle
    tenant = self.store_tenant(**tenant_data)
  File "/usr/local/lib/python3.7/site-packages/django_tenants/management/commands/create_tenant.py", line 85, in store_tenant
    tenant = get_tenant_model().objects.create(**fields)
  File "/usr/local/lib/python3.7/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/django/db/models/query.py", line 420, in create
    obj = self.model(**kwargs)
  File "/usr/local/lib/python3.7/site-packages/django/db/models/base.py", line 483, in __init__
    _setattr(self, field.name, rel_obj)
  File "/usr/local/lib/python3.7/site-packages/django/db/models/fields/related_descriptors.py", line 211, in __set__
    self.field.remote_field.model._meta.object_name,
ValueError: Cannot assign "'testowner'": "Client.owner" must be a "TenantUser" instance.

**Comment by mcquadenc** [comment]
Can you provider the Client definition and your User model?

The documentation explain that user should inherit from TenantUser (Especially the 'owner' attribute of Client model). Them exception seems notice this.

**Comment by Dresdn** [comment]
Documentation updates should address this issue.
