### ISSUE TITLE
App config issue with Django 3.2.x

### ISSUE THREAD

**Issue by philippbosch** [Corvia/django-tenant-users#70]
When running with Django 3.2 I'm getting the following error:

```
Traceback (most recent call last):
  File "manage.py", line 13, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/pb/Code/weg/venv/lib/python3.8/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
    utility.execute()
  File "/Users/pb/Code/weg/venv/lib/python3.8/site-packages/django/core/management/__init__.py", line 395, in execute
    django.setup()
  File "/Users/pb/Code/weg/venv/lib/python3.8/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/Users/pb/Code/weg/venv/lib/python3.8/site-packages/django/apps/registry.py", line 91, in populate
    app_config = AppConfig.create(entry)
  File "/Users/pb/Code/weg/venv/lib/python3.8/site-packages/django/apps/config.py", line 255, in create
    return app_config_class(app_name, app_module)
  File "/Users/pb/Code/weg/venv/lib/python3.8/site-packages/django/apps/config.py", line 38, in __init__
    raise ImproperlyConfigured(
django.core.exceptions.ImproperlyConfigured: The app label 'tenant_users.tenants' is not a valid Python identifier.
```

Guess this is due to the latest changes re: [automatic app config discovery](https://docs.djangoproject.com/en/3.2/releases/3.2/#automatic-appconfig-discovery) in 3.2. It was probably already broken before if you put `tenant_users.apps.TenantsConfig` into `INSTALLED_APPS`. But now the `TenantsConfig` is automatically discovered and used.

I believe this can be fixed by changing the app label to not contain a `.` and will provide a PR for this.

**Comment by risha700** [comment]
+1
