### ISSUE TITLE
User model query filters on id instead of defined primary key field

### ISSUE THREAD

**Issue by Jed-Giblin** [Corvia/django-tenant-users#707]
Provide a general summary of the issue in the title above.
During the `TenantModel.add_user` in `tenant.models.add_user` , a query is run against a set of user models to validate that the incoming new user isn't already a member of that tenant. 
```
if self.user_set.filter(id=user_obj.pk).exists():
```

This code does a filter on the `id` field which may not be present on the user model. It does correctly use the `pk` shortcut on the model its filtering by. Updating to:

```
if self.user_set.filter(pk=user_obj.pk).exists():
```

Would prevent any errors for user models without an `id` attribute

## Expected Behavior
The process of adding users to a tenant should proceed without error if the user model doesn't have an ID

## Actual Behavior
A traceback occurs:

```
Traceback (most recent call last):
  File "/manage.py", line 22, in <module>
    main()
  File "/manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "/venv/lib/python3.12/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "/venv/lib/python3.12/site-packages/django/core/management/__init__.py", line 436, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/venv/lib/python3.12/site-packages/django/core/management/base.py", line 413, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/venv/lib/python3.12/site-packages/django/core/management/base.py", line 459, in execute
    output = self.handle(*args, **options)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/venv/lib/python3.12/site-packages/tenant_users/tenants/management/commands/create_public_tenant.py", line 28, in handle
    create_public_tenant(domain_url=domain_url, owner_email=owner_email)
  File "/venv/lib/python3.12/site-packages/tenant_users/tenants/utils.py", line 111, in create_public_tenant
    public_tenant.add_user(profile, is_superuser=is_superuser, is_staff=is_staff)
  File "/venv/lib/python3.12/site-packages/tenant_users/tenants/models.py", line 59, in inner
    result = func(self, *args, **options)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/venv/lib/python3.12/site-packages/tenant_users/tenants/models.py", line 110, in add_user
    if self.user_set.filter(id=user_obj.pk).exists():
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/venv/lib/python3.12/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/venv/lib/python3.12/site-packages/django/db/models/query.py", line 1476, in filter
    return self._filter_or_exclude(False, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/venv/lib/python3.12/site-packages/django/db/models/query.py", line 1494, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "/venv/lib/python3.12/site-packages/django/db/models/query.py", line 1501, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "/venv/lib/python3.12/site-packages/django/db/models/sql/query.py", line 1609, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/venv/lib/python3.12/site-packages/django/db/models/sql/query.py", line 1641, in _add_q
    child_clause, needed_inner = self.build_filter(
                                 ^^^^^^^^^^^^^^^^^^
  File "/venv/lib/python3.12/site-packages/django/db/models/sql/query.py", line 1491, in build_filter
    lookups, parts, reffed_expression = self.solve_lookup_type(arg, summarize)
                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/venv/lib/python3.12/site-packages/django/db/models/sql/query.py", line 1303, in solve_lookup_type
    _, field, _, lookup_parts = self.names_to_path(lookup_splitted, self.get_meta())
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/venv/lib/python3.12/site-packages/django/db/models/sql/query.py", line 1768, in names_to_path
    raise FieldError(
django.core.exceptions.FieldError: Cannot resolve keyword 'id' into field. Choices are: auth_token, customer, email, guid, is_active, is_verified, last_login, logentry, password, tenants, type, usertenantpermissions

## Possible Fix
See description of issue, but simply changing the filtered column to pk works.

## Steps to Reproduce
1. Create a user model that doesn't have an id:
```
from tenant_users.tenants.models import UserProfile
import uuid

class AppUser(UserProfile):
    guid = models.UUIDField(primary_key=True, default=uuid.uuid4)
```
2. Follow the rest of the steps in the installation details of the repo.

## Your Environment
Include relevant details about the environment you experienced the bug in.
django-tenant-users==2.0.0
django-tenants==3.7.0
djangorestframework==3.15.2
Django==5.1.3

OSX Sonoma
Python 3.12

**Comment by Dresdn** [comment]
Feel free to open a PR!

**Comment by Jed-Giblin** [comment]
PR opened!
