### ISSUE TITLE
Delete a user

### ISSUE THREAD

**Issue by Melendeze13** [Corvia/django-tenant-users#714]
Hello,

I'm wondering if a user can be deleted instead of being deactivated.
In the United States, some state laws require data to be deleted if an individual requests so.

Currently the framework only allows users to be deactivated. This is not enough as the user data is still available in the database.
Maybe other steps can take place such as scrambling the data fields so user is unidentifiable.

Anyhow, when removing a user using delete(), I run into an issue. I'm wondering if this is the reason a proper delete was never added.

Note that the user is only part of the public schema and role is a tenant app which references the a user:
    employee = models.OneToOneField(
        CustomUser, on_delete=models.CASCADE, related_name="role", null=True, blank=True
    )

>>> from django.contrib.auth import get_user_model
>>> users = get_user_model()
>>> users.objects.filter(email="test@test.com").delete()

django.db.utils.ProgrammingError: relation "role_role" does not exist
LINE 1: ...role_role"."duty", "role_role"."employee_id" FROM "role_role...

>>> test = users.objects.get(email="test@test.com")
>>> test.delete()
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/usr/local/lib/python3.10/site-packages/tenant_users/tenants/models.py", line 399, in delete
    raise DeleteError(
tenant_users.tenants.models.DeleteError: UserProfile.objects.delete_user() should be used.

>>> test.delete(force_drop=True)
django.db.utils.ProgrammingError: relation "role_role" does not exist
LINE 1: ...role_role"."duty", "role_role"."employee_id" FROM "role_role...
                                                             ^
Thanks,
Elmer Melendez

**Comment by Dresdn** [comment]
IINAL, but to comply with GDPR or CCPA, you can either delete the object or scrub the PII (eg. `email` field), depending on various laws and your architecture.

If you want to delete the object permanently, you have a couple of ways:

### Signal
```python
from tenant_users.permissions.signals import tenant_user_deleted

@receiver(tenant_user_deleted)
def handle_tenant_user_deleted(sender, **kwargs):
    user = kwargs.get('user')
    if user:
      user.delete(force_drop=True)
```

### Without Signal

```python
my_user = TenantUser.objects.get()

# Use manager to clear tenant permissions
TenantUser.objects.delete_user(my_user)

# Permanently delete the object
my_user.delete(force_drop=True)
```

**Comment by Melendeze13** [comment]
Thank you for providing feedback. In our codebase we remove the user without a signal.
The same way you mentioned.

This causes this specific issue:
```bash
db-1  | 2024-12-04 00:07:28.847 UTC [252] ERROR:  relation "role_role" does not exist at character 116
db-1  | 2024-12-04 00:07:28.847 UTC [252] STATEMENT:  SELECT "role_role"."id", "role_role"."name", "role_role"."pay", "role_role"."duty", "role_role"."employee_id" FROM "role_role" WHERE "role_role"."employee_id" IN (1)
```

We have another model called "Role". It's part of the tenant apps not the shared apps.
When we create a user for any schema, when we delete that user, it seems it's looking for a table only available in the tenant apps due to the on_delete=models.CASCADE. Is there a way to avoid this? I would like to keep the CASCADE behavior.

I also want to note if our on_delete is set to DO_NOTHING this issue is not seen but we have a lingering Role with no user.
```python
# Part of role.models.Role

# Issue occurs
    employee = models.OneToOneField(
        CustomUser,
        on_delete=models.CASCADE,
        related_name="role",
        null=True,
        blank=True,
    ) 


# Avoid issue
 employee = models.OneToOneField(
        CustomUser,
        on_delete=models.DO_NOTHING,
        related_name="role",
        null=True,
        blank=True,
    )
```

**Comment by Dresdn** [comment]
You're venturing into core [django-tenants](https://github.com/django-tenants/django-tenants) territory now as this isn't really an issue with DTU, but more of how public-tenant relationships work. There was a recent issue here, and multiple on django-tenants, about this.

The short of it is that you can't (easily) use a two-way relationship between a Tenant Schema and the Public Schema within the Public Schema. Since DTU puts the UserModel in the public schema, using CASCADE won't work as the public schema has no knowledge of the tenant schemas.

You'll need to write your own manager method of deleting your Role objects. I would mirror it off of the `delete_user()` method.
